export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",

  SET_NEW_PLAYLIST_NAME: "SET_NEW_PLAYLIST_NAME",
  SET_CONTEXT_MENU: "SET_CONTEXT_MENU", // Thêm hằng số cho context menu
  SET_SELECTED_PLAYLIST_ID: "SET_SELECTED_PLAYLIST_ID", // Thêm hằng số cho playlist được chọn
  
  REFRESH_PLAYLIST: "REFRESH_PLAYLIST",
  CLEAR_SELECTED_PLAYLIST: "CLEAR_SELECTED_PLAYLIST",
  SET_SELECTED_ALBUM_ID: "SET_SELECTED_ALBUM_ID",
};
